[package]
name = "blink"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
stm32f3xx-hal = { version = "0.10", features = ["stm32f303xc", "rt"] }
panic-halt = "0.2"